.PHONY: clean All

All:
	@echo "----------Building project:[ arvore - Debug ]----------"
	@$(MAKE) -f  "arvore.mk"
clean:
	@echo "----------Cleaning project:[ arvore - Debug ]----------"
	@$(MAKE) -f  "arvore.mk" clean
