.PHONY: clean All

All:
	@echo "----------Building project:[ ninjacode - Debug ]----------"
	@$(MAKE) -f  "ninjacode.mk"
clean:
	@echo "----------Cleaning project:[ ninjacode - Debug ]----------"
	@$(MAKE) -f  "ninjacode.mk" clean
