.PHONY: clean All

All:
	@echo "----------Building project:[ lista_enc_dinam - Debug ]----------"
	@$(MAKE) -f  "lista_enc_dinam.mk"
clean:
	@echo "----------Cleaning project:[ lista_enc_dinam - Debug ]----------"
	@$(MAKE) -f  "lista_enc_dinam.mk" clean
