.PHONY: clean All

All:
	@echo "----------Building project:[ fila_dinamica - Debug ]----------"
	@$(MAKE) -f  "fila_dinamica.mk"
clean:
	@echo "----------Cleaning project:[ fila_dinamica - Debug ]----------"
	@$(MAKE) -f  "fila_dinamica.mk" clean
