.PHONY: clean All

All:
	@echo "----------Building project:[ pilha_dinamica - Debug ]----------"
	@$(MAKE) -f  "pilha_dinamica.mk"
clean:
	@echo "----------Cleaning project:[ pilha_dinamica - Debug ]----------"
	@$(MAKE) -f  "pilha_dinamica.mk" clean
